### ISSUE TITLE
"How to use" not works based on the README

### ISSUE THREAD

**Issue by mrvahedi68** [Rezakazemi890/Bulk-proto-to-C-sharp-class-converter#3]
Please note that the first step of [How to Use](https://github.com/Rezakazemi890/Bulk-proto-to-C-sharp-class-converter#how-to-use) appears to be incorrect. The repository address provided in the `Clone the Repository` section needs verification or correction.

**Comment by Rezakazemi890** [comment]
thanks @mrvahedi68 fixed issue at https://github.com/Rezakazemi890/Bulk-proto-to-C-sharp-class-converter/pull/4
